### ISSUE TITLE
Can we have in english version.

### ISSUE THREAD

**Issue by ranjeet-floyd** [davideuler/architecture.of.internet-product#1]

**Comment by davideuler** [comment]
Hi, Floyd, it's a good idea.  Thanks for your ticket.  

What's the content contained in the English version would help for people to learn the technique architecture of internet product?

And which products(Like Goolge/Facebook/Amazon/Twitter/Netflix?) do you think could represents typical architecture technique for nowaday internet product ?

I hope the English version could contain contents as little as possible, while covering typical architecture models for internet products as many as possible.
