### ISSUE TITLE
这项目价值有限，急需改进

### ISSUE THREAD

**Issue by xxllp** [davideuler/architecture.of.internet-product#3]
恕我直言，这个项目真的没啥价值，难道不是应该列点详细的 项目 使用和新技术吗？只包含文件算程序员的作为吗

**Comment by imfht** [comment]
@xxllp 有个人归归类，挺好的，看起来也方便。

**Comment by Jiayi-Liao** [comment]
确实有一些没有干货，但是不排除有好的东西，
建议博主把控一下内容质量吧。。。。。。

**Comment by davideuler** [comment]
好建议， 慢慢来  @xxllp   朋友们也可以提 PR 过来 😄

多谢 @buptljy

**Comment by xxllp** [comment]
文件不是代码，不好搜索，有些还要下载。每个文档都是来自网上，虽有归类，最好还是有个md 总述下具体每个里面会包含啥，不然总感觉分类有点乱 ，文档也存在过时等各种问题。

**Comment by xxllp** [comment]
一点都不github ，完全文档话的话

**Comment by davideuler** [comment]
非常感谢 @xxllp 😄 给你个赞， 待我抽空总述一些重要的文档。

**Comment by baiyutang** [comment]
@xxllp @buptljy @imfht 其实我不懂这个项目为啥这么高的star, 资料还有些旧了。我的资料都是持续更新的。请指导：

https://github.com/baiyutang/meetup

**Comment by imfht** [comment]
@baiyutang 以会议为维度的分类实际上价值不是很大。
这个repo厉害之处在于作者对这些资料进行了整理，比如说我想看看某个开源组件在大厂是怎么样落地的，大厂踩过哪些坑，在这个repo里面能看到。

**Comment by baiyutang** [comment]
@imfht  如果我按照他的思路走  那不重复咯

**Comment by zhangenqiang0229** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
