### ISSUE TITLE
可以把 PPT 传到云平台上

### ISSUE THREAD

**Issue by welefen** [davideuler/architecture.of.internet-product#5]
建议把 PPT 传到云平台上（如： https://ppt.baomitu.com/ ，单个 PPT 地址 https://ppt.baomitu.com/d/05450239 ），这样打开会很快，这个项目只用维护个介绍和地址就可以了。

**Comment by davideuler** [comment]
会考虑上传到国内的网盘或者gitee之类的，方便大家批量下载，离线阅读，多谢反馈。
